sudo: required
dist: trusty
language: c

matrix:
  fast_finish: true
  # list only supported gcc versions: https://gcc.gnu.org/
  include:
    # https://wiki.ubuntu.com/ToolChain#GCC
    # https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: COMPILER=gcc-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env: COMPILER=gcc-6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env: COMPILER=gcc-7
    # http://releases.llvm.org/
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang-3.8
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      env: COMPILER=clang-3.9

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install automake autopoint gettext xsltproc docbook-xml docbook-xsl libxml2-utils

script:
  - $COMPILER --version
  - autopoint --version
  - ./autogen.sh
  - ./configure CC=$COMPILER --disable-prelude --enable-regenerate-docu
  - make
  - make check
  - make distcheck

# vim:et:ts=2:sw=2
